sudo: false

language: python
python:
  - "3.6"

addons:
  sonarcloud:
    organization: "suminb-github"

install:
  - pip install -r requirements.txt
  - pip install -r web/tests/requirements.txt

script:
  - export PYTHONPATH=$PYTHONPATH:.
  - py.test --cov web --cov-report term-missing --durations=10

after_success:
  - coveralls
  - sonar-scanner
