language: python
sudo: false

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - export PYTHONPATH=$PYTHONPATH:.
  - py.test --cov web --cov-report term-missing --durations=10

after_success:
  - coveralls
