sudo: false

language: python
python:
  - "3.7"
  - "3.8-dev"

addons:
  sonarcloud:
    organization: "suminb-github"

install:
  - pip install -r requirements.txt
  - pip install -r web/tests/requirements.txt
  - pip install black

script:
  - export PYTHONPATH=$PYTHONPATH:.
  - black --check .
  - py.test --cov web --cov-report term-missing --durations=10

after_success:
  - coveralls
  - sonar-scanner
