language: python
sudo: false

python:
  - "2.7"
  - "3.5"

install:
  - pip install -r requirements.txt --use-mirrors

script:
  - export PYTHONPATH=$PYTHONPATH:.
  - py.test tests --cov app --durations=10

after_success:
  - coveralls
