language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt --use-mirrors

script:
  - echo "Currently has no test case."
  - export PYTHONPATH=$PYTHONPATH:.
  - py.test tests --cov app --durations=10

after_success:
  - coveralls
